apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: patchmanager-deployment 
spec: 
  selector: 
    matchLabels: 
      app: patchmanager 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: patchmanager 
    spec: 
      containers: 
      - name: patchmanager 
        image: intrusivebaguettes/patchmanager:development
        ports: 
        - containerPort: 13000