apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: restapi-deployment 
spec: 
  selector: 
    matchLabels: 
      app: restapi 
  replicas: 1
  strategy:
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: restapi 
    spec: 
      containers: 
      - name: restapi 
        image: intrusivebaguettes/restapi:development
        ports: 
        - containerPort: 80
        imagePullPolicy: Always