apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: servermanager-deployment 
spec: 
  selector: 
    matchLabels: 
      app: servermanager 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata: 
      labels: 
        app: servermanager 
    spec:      
      containers:
      - name: servermanager
        image: intrusivebaguettes/servermanager:development
        ports: 
        - containerPort: 27001
        - containerPort: 27002
        imagePullPolicy: Always      
        volumeMounts:
          - name: kubectl-binary
            mountPath: /usr/bin/kubectl
            readOnly: true
          - name: kubectl-config
            mountPath: /etc/kubernetes/config
            readOnly: true
      volumes:
        - name: kubectl-binary
          hostPath:
            path: /usr/bin/kubectl
        - name: kubectl-config
          hostPath:
            path: /etc/kubernetes/config