apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: patchmanager-deployment 
spec: 
  selector: 
    matchLabels: 
      app: patchmanager 
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata: 
      labels: 
        app: patchmanager 
    spec: 
      containers: 
      - name: patchmanager 
        image: intrusivebaguettes/patchmanager:development
        ports: 
        - containerPort: 13000
        imagePullPolicy: Always