apiVersion: batch/v1
kind: Job
metadata:
  generateName: "game-"
spec:
  restartPolicy: Never
  ttlSecondsAfterFinished: 5
  template:
    spec:
      hostNetwork: true
      restartPolicy: Never
      containers:
      - name: gameserver
        # image: intrusivebaguettes/gameserver:development
        image: eehmm/server-temp
        env:
        - name: SESSION_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name