apiVersion: v1
kind: Pod
metadata:
  name: "mame-server-instance"
spec:
  hostNetwork: true
  restartPolicy: Never
  containers:
    - name: game-server
      image: intrusivebaguettes/gameserver:development