kind: Service 
apiVersion: v1 
metadata: 
  name: restapi-service 
spec: 
  selector: 
    app: restapi 
  type: NodePort
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80
    nodePort: 30830